### ISSUE TITLE
Did you get the idea from Drupal Module?

### ISSUE THREAD

**Issue by killua99** [drubage/stage-file-proxy#1]
I was wonder if you get the idea to build this plugin from the drupal module. https://www.drupal.org/project/stage_file_proxy

Seems they have exact the same name, I'll like to know if this has the same features or if you plan to implement them, if so, would you like to mention that this plugin does or doesn't the same has the Drupal one.

**Comment by drubage** [comment]
Definitely! We love Drupal and use stage_file_proxy all the time and we wanted something similar for Wordpress. I don't plan on adding all the features of the Drupal module, we just added what we needed to speed up our local development and make tracking projects and their dependencies easier.

**Comment by killua99** [comment]
Thanks for clarify it <3 nice port!
